### ISSUE TITLE
Fat Pig texture corruption

### ISSUE THREAD

**Issue by ili0s** [ArtixAllMighty/FatChickens#1]
Note: Mob variants skin textures are enabled but look unrelated to the issue as the fat chicken and fat salmon textures render as they should.

See attached file for reference

![Java-runtime-beta Screenshot 2022 01 06 - 01 03 41 50](https://user-images.githubusercontent.com/97202024/148307395-d41ca560-fe72-44c4-8105-68bfe5abdd66.png)

**Comment by AbsolemJackdaw** [comment]
wait what ? xD
Is that a pig ? 
this is so weird. fat pigs are just pigs, they use the vanilla model, but with an inflated torso. 

what other mods do you have installed ?
Could you test without the mob variant skins texture ? 
I don't even recognize the pig skin texture in that mess of a mob XD !

any resource packs installed ? 
optifine maybe ? they may mess with the model and offsets .. i don't immediatly know what to think of this. 

My first guess is another mod messing with models. 
could you debug and test a bit for me with the mods you got installed ?

**Comment by ili0s** [comment]
yes, although i believe the texture is jumbled around? sorta like how the creeper became a creeper ya know xD well basically i have variant skins enabled right - and nothing else that should affect vanilla mobs textures. I have quite a few mods enabled as its a heavily modded server im running. What I found interesting is that testing on the chicken and salmon they didn't get affected at all despite also having variant skins, they went from their variant skin (fat chicken in the back was originally brown) and then went to the fat state looking fine. Which is why i made the conclusion that perhaps it isnt the variant skin texture im using causing this as i assume the other models would also be affected if that was the case? I do have optifine and etc so i will try to debug it a bit for you when i get time :)

**Comment by AbsolemJackdaw** [comment]
https://github.com/ArtixAllMighty/FatChickens/blob/master/src/main/java/be/jackdaw/fatchicken/entity/render/pig/FatPigRenderer.java#L10

the pigs, as well as other mobs, use the same path to the texture as their regular counter parts. 

The only time I've seen issues like this is when the texture size was too big and the mapping was off. 
So my guess is on a mod that changes the model of the pig, and thus changes the mapping of what piece of the pig goes where.

**Comment by AbsolemJackdaw** [comment]
Marked as stale. Concidered solved by lack of response.
feel free to reopen if issue persists.
if you have optifine installed, try running it without optifine too. its known to mess with mods and more so with rendering
