### ISSUE TITLE
[Quilt] Crash on startup with Vanity Splash Text

### ISSUE THREAD

**Issue by SplendidAlakey** [ArtixAllMighty/FatChickens#3]
**MC** 1.19.2
**QSL** 4.0.0-beta13
**FatChicken** 2.0.1
**[VanitySplashText](https://www.curseforge.com/minecraft/mc-mods/vanity-splash-text)** 1.1.0

The game crashes on startup with both mods installed. I believe it happens because your mod's version is internally marked as `${version}`. Blacklisting your mod from vanity splashes lets the game start normally, but of course, I'd like to let it show your mod as well.

Logs: https://gist.github.com/Footage2-Amply-Pounce/3dd7cd8bcbe173252148a8115628dde5

**Comment by AbsolemJackdaw** [comment]
fixed in 7372280e5166df55648efeccc30cba4f3e838c21
